### ISSUE TITLE
Can't run at all in Corona

### ISSUE THREAD

**Issue by Rodayan** [wolfgangjiang/tetris-lua#2]
Hi this has problems running in Corona. I am totally new to this and have no idea what 'love' format or whatever it is.

Problems in Corona:
module 'underscore' not found
underscore.lua or underscore.dll no file found (it looks in a bunch of places and still finds no file)
What is this underscore file or files and can you post it so I can try and look at your game?

I really just want to know how to code tetris type shapes and rotating them and placing them on a grid not allowing overlapping.

Thanks!

**Comment by wolfgangjiang** [comment]
'underscore.lua' is a third-party utility library of Lua!
You can refer to https://mirven.github.io/underscore.lua/ and https://github.com/mirven/underscore.lua for details. 

Also, you can learn info about Love2d the game framework
at https://love2d.org/ . Due to the simplistic nature of this classic 
game, I don't think it would be difficult to adapt my code to
another game framework like Corona by yourself.
